### ISSUE TITLE
Unable to run games via CSpect?  "Fatal Error: Unable to find game file."

### ISSUE THREAD

**Issue by Dion-Guy** [stefanbylund/zxnext_level9#2]
I have spent some time trying to get any of the Level 9 games working with CSpect.  I have tried multiple versions of CSpect including the latest (2.19.6.0), but every time I get the same error.

When I run any game's run_cspect.bat file it loads CSpect, and then loads level9_512.nex, but I get a screen that says:

> Level 9 Interpreter for ZX Spectrum Next 1.0.0

> Fatal Error: Unable to find game file.

I have set the CSpect directory in PATH and haven't altered the unzipped level9.zip's file structure.  On some of the games (e.g. Scapeghost and Lancelot) it displays a title screen first but then goes to the error screen.  I have tried amending the batch file to load level9_256.nex instead, but get the same results.

Apologies if I am doing something stupid, but I have followed the instructions and just can't figure out what is wrong.  Any help would be much appreciated!

**Comment by stefanbylund** [comment]
I used an older version of CSpect when testing the Level 9 compilation in CSpect. It works fine up to version 2.15.2 of CSpect. Starting with version 2.16.0, you get the error message "Fatal Error: Unable to find game file.".

The problem seems to be the esx_f_stat() function in Z88DK which uses the esxDOS F_STAT call. This function is used to determine if the game is a single-file game (gamedata.dat) or a multi-file game (gamedat1.dat, gamedat2.dat, ...). The esx_f_stat() function returns zero if the F_STAT call was successful and non-zero if an error occurred.

CSpect simulates a subset of the esxDOS calls on top of the host file system. In CSpect 2.15.2 and earlier, the simulated esxDOS F_STAT call worked fine when CSpect was started with the -mmc option and a specified directory. Maybe esxDOS F_STAT only works with an actual SD card image in CSpect 2.16.0 and later, and not in its simulated form? I will consult with the CSpect author.

As a workaround you can use CSpect 2.15.2. Please let me know if this works for you.

**Comment by Dion-Guy** [comment]
Thanks for looking at this so quickly.  I can confirm that the games work fine with CSpect 2.15.2.  Unfortunately I didn't go back that far with my testing, but it's good that you have identified this problem with the later versions of CSpect.

**Comment by stefanbylund** [comment]
Fixed in CSpect v2.19.6.1.
